# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [ 'serve' ]
  serve:
    deps: [ 'assets/copy' ]
    cmds:
      - hugo serve
  build:
    deps: [ 'assets/copy' ]
    cmds:
      - hugo
  assets/copy:
    cmds:
      - install -D $resume/resume.pdf static/assets/pdf/resume.pdf
      - install -D $license_icon themes/PaperMod/assets/png/cc-by-nd-80x15.png
  deploy:
    deps: [ 'build' ]
    cmds:
      - aux/deploy
